version: '3'

services:
  flask-app:
    image: python:3.9-slim
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]
